### PR TITLE
Extract package bugfix

### LINKED ISSUE #318: Publishing components
OC version: 0.33.22
node: 6.5.0

When trying to publish a new component to a registry, I get  the following error:
```
An error happened when publishing the component: TypeError: targz.extract is not a function
    at module.exports (/usr/src/app/node_modules/oc/src/registry/domain/extract-package.js:16:9)
    at /usr/src/app/node_modules/oc/src/registry/routes/publish.js:43:5
    at callbacks (/usr/src/app/node_modules/oc/node_modules/express/lib/router/index.js:164:37)
    at options.beforePublish (/usr/src/app/node_modules/oc/src/registry/domain/options-sanitiser.js:14:55)
    at callbacks (/usr/src/app/node_modules/oc/node_modules/express/lib/router/index.js:164:37)
    at param (/usr/src/app/node_modules/oc/node_modules/express/lib/router/index.js:138:11)
    at param (/usr/src/app/node_modules/oc/node_modules/express/lib/router/index.js:135:11)
    at param (/usr/src/app/node_modules/oc/node_modules/express/lib/router/index.js:135:11)
    at pass (/usr/src/app/node_modules/oc/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/usr/src/app/node_modules/oc/node_modules/express/lib/router/index.js:173:5)
```

The documentation for the package ```targz``` (https://www.npmjs.com/package/targz) says to use the function ```decompress``` instead of ```extract```

Am I missing something ? Any help appreciated :)

### PR DESCRIPTION
**Pull request by matteofigus**
Fixes #318 

It turns out this was introduced with #316 - I added a unit test to ensure we are making the right call to the targz dependency.

### CODE REVIEW

File: test/unit/registry-domain-extract-package.js [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+        response = res;
+        done();
+      });
+    });
+
+    it('should decompress tar.gz file', function(){
+      expect(decompressStub.args[0][0]).to.eql({
+        dest: '/some-path/registry/temp/1478279453422/',
+        src: '/some-path/registry/temp/1478279453422.tar.gz'
+      });
```
Comment (mattiaerre) [inline test/unit/registry-domain-extract-package.js]: would you mind to swap the properties order? `src` then `dest` plz? 😅

File: test/unit/registry-domain-extract-package.js [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+      decompressStub.yields();
+
+      extractPackage({
+        '1478279453422.tar.gz': {
+          name: '1478279453422.tar.gz',
+          path: '/some-path/registry/temp/1478279453422.tar.gz'
+        }
+      }, function(err, res){
+        error = err;
+        response = res;
```
Comment (mattiaerre) [inline test/unit/registry-domain-extract-package.js]: I think you should assert against `res` as it is what your component actually returns; maybe also add a test against the sad path?

Comment (matteofigus) [inline test/unit/registry-domain-extract-package.js]: Done
